import OpenAI from "openai";
import { openAIApiKey } from './config.js';
const openai = new OpenAI({apiKey: openAIApiKey, dangerouslyAllowBrowser: true});

const form = document.querySelector("#posterForm");
const floorArea = document.querySelector("#floor-area");
const bhkType = document.querySelector("#bhk-type");
const posterOutput = document.querySelector("#poster-output");

form.addEventListener("submit", function (event) {
  event.preventDefault();
  posterOutput.innerHTML = `Generating floor plan of "${floorArea.value.trim()}" square foot for ${bhkType.value}...`;
  const prompt = `A clean, 2D top-down floor plan of a modern ${bhkType.value} one floor apartment with area equal to "${floorArea.value.trim()}" square feet with rooms labeled (such as master bedroom, living room, kitchen, entrance, foyer, bathroom, study room, kids bedroom, guest bedroom etc.), realistic proportions, and a minimal number of sections.`
  generatePoster(prompt);
  console.log(prompt);
  form.reset();
});

async function generatePoster(prompt) {
  try {
    const image = await openai.images.generate({
      model: "dall-e-3",
      prompt
    });
    const imgURL = image.data[0].url;
    posterOutput.innerHTML = `<img src="${imgURL}" alt="Imaginative floor plan generated by AI.">`;
  } catch (error) {
    console.error(error);
    posterOutput.innerHTML = "Failed to generate floor plan. Please try again.";
  }
}
